-- Reset data generated by the 7500-student k6 load test.
--
-- Scope:
-- - stress-test students only: 22990001 ~ 22997500
-- - removes their enrollments / likes / comments / notifications / selection requests
-- - recalculates affected course counters
-- - resets these students' credit_used back to 0
--
-- This script is intended for a local test database.
-- After running it, also clear Redis selection cache before starting the next round.

START TRANSACTION;

DROP TEMPORARY TABLE IF EXISTS tmp_stress_students;
CREATE TEMPORARY TABLE tmp_stress_students AS
SELECT id
FROM students
WHERE student_no BETWEEN '22990001' AND '22997500';

DROP TEMPORARY TABLE IF EXISTS tmp_affected_courses;
CREATE TEMPORARY TABLE tmp_affected_courses (
  id BIGINT UNSIGNED NOT NULL PRIMARY KEY
);

INSERT IGNORE INTO tmp_affected_courses (id)
SELECT DISTINCT e.course_id
FROM enrollments AS e
JOIN tmp_stress_students AS s ON s.id = e.student_id;

INSERT IGNORE INTO tmp_affected_courses (id)
SELECT DISTINCT l.course_id
FROM course_likes AS l
JOIN tmp_stress_students AS s ON s.id = l.student_id;

INSERT IGNORE INTO tmp_affected_courses (id)
SELECT DISTINCT cc.course_id
FROM course_comments AS cc
JOIN tmp_stress_students AS s ON s.id = cc.student_id;

DELETE FROM notifications
WHERE recipient_type = 1
  AND recipient_id IN (SELECT id FROM tmp_stress_students);

DELETE FROM selection_requests
WHERE student_id IN (SELECT id FROM tmp_stress_students);

DELETE FROM course_likes
WHERE student_id IN (SELECT id FROM tmp_stress_students);

DELETE FROM course_comments
WHERE student_id IN (SELECT id FROM tmp_stress_students);

DELETE FROM enrollments
WHERE student_id IN (SELECT id FROM tmp_stress_students);

UPDATE students
SET credit_used = 0
WHERE id IN (SELECT id FROM tmp_stress_students);

UPDATE courses AS c
LEFT JOIN (
  SELECT course_id, COUNT(*) AS selected_cnt
  FROM enrollments
  WHERE status = 1
  GROUP BY course_id
) AS e ON e.course_id = c.id
LEFT JOIN (
  SELECT course_id, COUNT(*) AS like_cnt
  FROM course_likes
  GROUP BY course_id
) AS l ON l.course_id = c.id
LEFT JOIN (
  SELECT course_id, COUNT(*) AS comment_cnt
  FROM course_comments
  WHERE status = 1
  GROUP BY course_id
) AS cc ON cc.course_id = c.id
SET
  c.selected_count = COALESCE(e.selected_cnt, 0),
  c.like_count = COALESCE(l.like_cnt, 0),
  c.comment_count = COALESCE(cc.comment_cnt, 0)
WHERE c.id IN (SELECT id FROM tmp_affected_courses);

COMMIT;
